name: Budget Planner Build
run-name: ${{ github.actor }} is building a new spk
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started"
      - name: Checkout Synology Repository
        uses: actions/checkout@v3
        with: 
          repository: SynologyOpenSource/pkgscripts-ng
          path: ${GITHUB_WORKSPACE}/synology
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ${GITHUB_WORKSPACE}/repo
      - run: ls -la repo
      - run: ls -la synology